### ISSUE TITLE
Github pages not load images

### ISSUE THREAD

**Issue by arrlancore** [arrlancore/react-coming-soon-template#27]
After build the github pages to https://arrlancore.github.io/react-coming-soon-template/ , image background is not appear.

**Comment by Vinetos** [comment]
This background image link is giving a 404 error :
![image](https://user-images.githubusercontent.com/10145351/66191714-3d9e3100-e68f-11e9-8ccd-3c5864aa9b98.png)

**Comment by arrlancore** [comment]
> This background image link is giving a 404 error :
> ![image](https://user-images.githubusercontent.com/10145351/66191714-3d9e3100-e68f-11e9-8ccd-3c5864aa9b98.png)
> 
> The issue is closed. Do you need help ?

Sorry my bad, should be not closed. Yes I also see the 404. Do you have any idea why?

**Comment by rowhitswami** [comment]
Let me take this up

**Comment by martink-rsa** [comment]
The issue is that the image is referenced as: 
[]
This links to the following where you will see that it does not include the repo (react-coming-soon-template):
https://arrlancore.github.io/static/bg-coming-soon-8c63f78b338c490c72be7355de424730.jpeg

You will see that the image is at the following address:
https://arrlancore.github.io/react-coming-soon-template/static/bg-coming-soon-8c63f78b338c490c72be7355de424730.jpeg

The filepath needs a period (.) in the front which will then correctly add the repo to the URL:
`background-image: url(./static/bg-coming-soon-8c63f78b338c490c72be7355de424730.jpeg);`

You will then see the image is correctly referenced. [Imgur link](https://imgur.com/gTYuRP6)

Be careful of when you develop locally as GitHub Pages will always add your repo name (github.io/name/repo/index.html) whereas when you develop locally on something such as LiveServer (VSCode Extension), it is going to have a root address such as `192.168.1.10/index.html` . Adding a period `.` at the start of the path should solve this for you moving forward.

**Comment by arrlancore** [comment]
Thanks all for sugesting, try using netlify and the issue solved. Now we build on https://react-coming-soon-template.netlify.com/
